
meta_product_name: "Socialite"
meta_title: "Recommendations - from people you actually trust"
meta_description: "Find new places from your social network to improve your social life."
meta_image: "meta.png" # should exist in `app/assets/images/`
